name: Auto Author Assign

on:
  pull_request_target:
    types: [ opened, reopened ]

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: arc-runners-small
    timeout-minutes: 30
    if: ${{ !github.event.pull_request.assignee }}
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.0
